dist: trusty
sudo: required

language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

matrix:
  fast_finish: true

install:
  - mvn install -B -DskipTests

script:
  - mvn package -B -DskipTests
  - mvn test -Ptest -B

notifications:
  email: false
